v1.4.10: Force creating the branch

diff --git a/pack_packer.yml b/pack_packer.yml
--- a/pack_packer.yml
+++ b/pack_packer.yml
@@ -41,7 +41,7 @@
       	local formatted_change
       
       	if [[ "$original_size" -eq 0 ]]; then
-      		formatted_change="-inf"
+      		formatted_change="+inf"
       	elif [[ "$new_size" -eq "$original_size" ]]; then
       		formatted_change="±0.00"
       	else
@@ -110,25 +110,29 @@
       result_file="$2"
       [[ "$optimize" ]] || result_file="${result_file/\.zip/_DEV.zip}"
       
+      if [[ ! -d "$base_folder" ]]; then
+      	echo "ERROR: Pack folder $base_folder doesn't exist!"
+      	exit 1
+      fi
+      
       # Detect installed tools
       jq_installed="$(command_exists jq)"
       ffmpeg_installed="$(command_exists ffmpeg)"
       oxipng_installed="$(command_exists oxipng)"
       optipng_installed="$(command_exists optipng)"
+      advzip_installed="$(command_exists advzip)"
       
       if [[ "$optimize" ]]; then
       	[[ "$jq_installed" ]] || echo "WARNING: jq is not installed! Cannot optimize JSON files!"
       	[[ "$ffmpeg_installed" ]] || echo "WARNING: ffmpeg is not installed! Cannot optimize OGG files!"
       	[[ "$oxipng_installed" || "$optipng_installed" ]] || echo "WARNING: neither oxipng, nor optipng is not installed! Cannot optimize PNG files!"
+      	[[ "$advzip_installed" ]] || echo "WARNING: advzip is not installed! Cannot recompress final zip!"
       fi
       
       # Shell options starting here
       set -e
       set -o pipefail
       shopt -s globstar
-      
-      # Ensure we're working relative to the script
-      cd "$(dirname "${BASH_SOURCE[0]}")"
       
       # Cleanup the last build if it still exists. The folder will be recreated in the loop
       rm -rf .build "$result_file"
@@ -255,7 +259,7 @@
       zip -9rq "../$result_file" .
       echo -e "\b\b\b DONE!"
       
-      if [[ "$optimize" ]]; then
+      if [[ "$optimize" && "$advzip_installed" ]]; then
       	cd ..
       
       	echo -en "\nRecompressing ${result_file}..."
