v1.4.1: Implement checking of optimization tools

diff --git a/pack_packer.yml b/pack_packer.yml
--- a/pack_packer.yml
+++ b/pack_packer.yml
@@ -84,6 +84,12 @@
       	fi
       }
       
+      function command_exists() {
+      	if command -v "$1" &>/dev/null; then
+      		echo 1
+      	fi
+      }
+      
       if [[ "$1" == "-h" || "$1" == "--help" ]]; then
       	print_help
       	exit
@@ -103,6 +109,18 @@
       base_folder="$1"
       result_file="$2"
       [[ "$optimize" ]] || result_file="${result_file/\.zip/_DEV.zip}"
+      
+      # Detect installed tools
+      jq_installed="$(command_exists jq)"
+      ffmpeg_installed="$(command_exists ffmpeg)"
+      oxipng_installed="$(command_exists oxipng)"
+      optipng_installed="$(command_exists optipng)"
+      
+      if [[ "$optimize" ]]; then
+      	[[ "$jq_installed" ]] || echo "WARNING: jq is not installed! Cannot optimize JSON files!"
+      	[[ "$ffmpeg_installed" ]] || echo "WARNING: ffmpeg is not installed! Cannot optimize OGG files!"
+      	[[ "$oxipng_installed" || "$optipng_installed" ]] || echo "WARNING: neither oxipng, nor optipng is not installed! Cannot optimize PNG files!"
+      fi
       
       # Shell options starting here
       set -e
@@ -138,12 +156,15 @@
       			cat "$source_file"
       			echo
       		) | sed -E '/^(\s*$|#)/d' | head -c-1 >"$target_file"
-      	elif [[ "$optimize" && "$source_file" =~ .*\.(json|mcmeta)$ ]]; then
+      	elif [[ "$optimize" && "$jq_installed" && "$source_file" =~ .*\.(json|mcmeta)$ ]]; then
       		jq -c . "$source_file" >"$target_file"
-      	elif [[ "$optimize" && "$source_file" =~ .*\.ogg$ ]]; then
+      	elif [[ "$optimize" && "$ffmpeg_installed" && "$source_file" =~ .*\.ogg$ ]]; then
       		cache ogg_v1 "$source_file" "$target_file" \
       			ffmpeg -hide_banner -loglevel error -y -i "$source_file" -c:a libopus -b:a 32k -ar 48000 -ac 2 -application audio -map_metadata -1 -flags:a +bitexact "$target_file"
-      	elif [[ "$optimize" && "$source_file" =~ .*\.png$ ]]; then
+      	elif [[ "$optimize" && "$oxipng_installed" && "$source_file" =~ .*\.png$ ]]; then
+      		cache png_v2 "$source_file" "$target_file" \
+      			oxipng --quiet -o max --fast --zopfli --strip safe --out "$target_file" -- "$source_file"
+      	elif [[ "$optimize" && "$optipng_installed" && "$source_file" =~ .*\.png$ ]]; then
       		cache png_v1 "$source_file" "$target_file" \
       			optipng -quiet -o7 -zm1-9 -strip all -out "$target_file" -- "$source_file"
       	else
